export const BLOCKCHAINS: Record<string, string> = {
  1: 'Ethereum',
  3: 'Ropsten',
  1666600000: 'Harmony',
  42: 'Kovan',
  4: 'Rinkeby',
  5: 'Goerli',
  56: 'Binance Smart Chain',
  97: 'Binance Smart Chain Testnet',
  137: 'Polygon',
  43114: 'Avalanche',
  waves: 'Waves',
  main: 'Waves',
  W: 'Waves',
}

export const BLOCKCHAIN_COINS: Record<string, string> = {
  1: 'ETH',
  3: 'ETH',
  1666600000: 'ONE',
  42: 'ETH',
  4: 'ETH',
  5: 'ETH',
  56: 'BNB',
  97: 'BNB',
  137: 'MATIC',
  43114: 'AVAX',
  waves: 'WAVES',
  main: 'WAVES',
  W: 'WAVES',
}
