export * from './protocol-list.graphql'
export * from './protocol-create.graphql'
export * from './protocol-detail.graphql'
export * from './protocol-delete.graphql'
export * from './protocol-detail-metric.graphql'
