export * from './staking-contract-list.graphql'
export * from './staking-contract-delete.graphql'
export * from './staking-contract-create.graphql'
export * from './staking-contract-update.graphql'
export * from './staking-disconnect-wallet.graphql'
export * from './staking-connect-wallet.graphql'
export * from './staking-tokens.graphql'
